[2021-03-07 13:07:25,986] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: check_minio_2.log 2021-03-06T00:00:00+00:00 [queued]>
[2021-03-07 13:07:25,997] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: check_minio_2.log 2021-03-06T00:00:00+00:00 [queued]>
[2021-03-07 13:07:25,998] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 13:07:25,998] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 13:07:25,998] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 13:07:26,008] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): log> on 2021-03-06T00:00:00+00:00
[2021-03-07 13:07:26,012] {standard_task_runner.py:52} INFO - Started process 49 to run task
[2021-03-07 13:07:26,015] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'check_minio_2', 'log', '2021-03-06T00:00:00+00:00', '--job-id', '113', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/check_minio_2/main.py', '--cfg-path', '/tmp/tmpugpx_vmt', '--error-file', '/tmp/tmp6lbgbwmh']
[2021-03-07 13:07:26,015] {standard_task_runner.py:77} INFO - Job 113: Subtask log
[2021-03-07 13:07:26,047] {logging_mixin.py:104} INFO - Running <TaskInstance: check_minio_2.log 2021-03-06T00:00:00+00:00 [running]> on host ded171213b30
[2021-03-07 13:07:26,083] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=check_minio_2
AIRFLOW_CTX_TASK_ID=log
AIRFLOW_CTX_EXECUTION_DATE=2021-03-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-06T00:00:00+00:00
[2021-03-07 13:07:26,083] {logging_mixin.py:104} INFO - Something happened in bucket
[2021-03-07 13:07:26,090] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=check_minio_2, task_id=log, execution_date=20210306T000000, start_date=20210307T130725, end_date=20210307T130726
[2021-03-07 13:07:26,113] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-07 13:07:26,148] {local_task_job.py:146} INFO - Task exited with return code 0
