[2021-03-03 19:29:22,946] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_email.get_ip 2021-03-03T19:29:21.860178+00:00 [queued]>
[2021-03-03 19:29:22,955] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_email.get_ip 2021-03-03T19:29:21.860178+00:00 [queued]>
[2021-03-03 19:29:22,955] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 19:29:22,955] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-03 19:29:22,955] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 19:29:22,962] {taskinstance.py:1063} INFO - Executing <Task(GetRequestOperator): get_ip> on 2021-03-03T19:29:21.860178+00:00
[2021-03-03 19:29:22,965] {standard_task_runner.py:52} INFO - Started process 46 to run task
[2021-03-03 19:29:22,967] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'send_email', 'get_ip', '2021-03-03T19:29:21.860178+00:00', '--job-id', '29', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/send_email.py', '--cfg-path', '/tmp/tmpgz8p2c2q', '--error-file', '/tmp/tmpxlqdp7fh']
[2021-03-03 19:29:22,967] {standard_task_runner.py:77} INFO - Job 29: Subtask get_ip
[2021-03-03 19:29:22,990] {logging_mixin.py:104} INFO - Running <TaskInstance: send_email.get_ip 2021-03-03T19:29:21.860178+00:00 [running]> on host 4c61e128b408
[2021-03-03 19:29:23,011] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=send_email
AIRFLOW_CTX_TASK_ID=get_ip
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T19:29:21.860178+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T19:29:21.860178+00:00
[2021-03-03 19:29:23,422] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=send_email, task_id=get_ip, execution_date=20210303T192921, start_date=20210303T192922, end_date=20210303T192923
[2021-03-03 19:29:23,439] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-03 19:29:23,461] {local_task_job.py:146} INFO - Task exited with return code 0
