[2021-03-03 20:55:44,818] {scheduler_job.py:182} INFO - Started process (PID=319) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:55:44,819] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 20:55:44,819] {logging_mixin.py:104} INFO - [2021-03-03 20:55:44,819] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:55:44,880] {logging_mixin.py:104} INFO - [2021-03-03 20:55:44,880] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 10, in <module>
    @dag(
NameError: name 'dag' is not defined
[2021-03-03 20:55:44,881] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:55:44,890] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.074 seconds
[2021-03-03 20:56:15,793] {scheduler_job.py:182} INFO - Started process (PID=349) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:56:15,793] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 20:56:15,794] {logging_mixin.py:104} INFO - [2021-03-03 20:56:15,794] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:56:15,865] {logging_mixin.py:104} INFO - [2021-03-03 20:56:15,864] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 10, in <module>
    @dag(
NameError: name 'dag' is not defined
[2021-03-03 20:56:15,865] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:56:15,876] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.086 seconds
[2021-03-03 20:56:46,777] {scheduler_job.py:182} INFO - Started process (PID=379) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:56:46,778] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 20:56:46,779] {logging_mixin.py:104} INFO - [2021-03-03 20:56:46,778] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:56:46,850] {logging_mixin.py:104} INFO - [2021-03-03 20:56:46,850] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 10, in <module>
    @dag(
NameError: name 'dag' is not defined
[2021-03-03 20:56:46,850] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:56:46,861] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.089 seconds
[2021-03-03 20:57:17,754] {scheduler_job.py:182} INFO - Started process (PID=409) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:57:17,756] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 20:57:17,757] {logging_mixin.py:104} INFO - [2021-03-03 20:57:17,757] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:57:17,839] {logging_mixin.py:104} INFO - [2021-03-03 20:57:17,839] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 10, in <module>
    @dag(
NameError: name 'dag' is not defined
[2021-03-03 20:57:17,839] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:57:17,850] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.100 seconds
[2021-03-03 20:57:48,706] {scheduler_job.py:182} INFO - Started process (PID=439) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:57:48,708] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 20:57:48,709] {logging_mixin.py:104} INFO - [2021-03-03 20:57:48,709] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:57:48,783] {logging_mixin.py:104} INFO - [2021-03-03 20:57:48,783] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 9, in <module>
    @dag(
NameError: name 'dag' is not defined
[2021-03-03 20:57:48,783] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:57:48,794] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.091 seconds
[2021-03-03 20:58:19,646] {scheduler_job.py:182} INFO - Started process (PID=469) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:58:19,647] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 20:58:19,648] {logging_mixin.py:104} INFO - [2021-03-03 20:58:19,648] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:58:19,705] {logging_mixin.py:104} INFO - [2021-03-03 20:58:19,705] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 10, in <module>
    start_date=days_ago(1),
NameError: name 'days_ago' is not defined
[2021-03-03 20:58:19,705] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:58:19,715] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.071 seconds
[2021-03-03 20:58:50,622] {scheduler_job.py:182} INFO - Started process (PID=499) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:58:50,622] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 20:58:50,623] {logging_mixin.py:104} INFO - [2021-03-03 20:58:50,623] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:58:50,735] {logging_mixin.py:104} INFO - [2021-03-03 20:58:50,735] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 15, in <module>
    start_date=days_ago(1),
NameError: name 'days_ago' is not defined
[2021-03-03 20:58:50,736] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:58:50,747] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.128 seconds
[2021-03-03 20:59:20,832] {scheduler_job.py:182} INFO - Started process (PID=529) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:59:20,833] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 20:59:20,834] {logging_mixin.py:104} INFO - [2021-03-03 20:59:20,834] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:59:20,966] {logging_mixin.py:104} INFO - [2021-03-03 20:59:20,966] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 21, in <module>
    start_date=days_ago(1),
NameError: name 'days_ago' is not defined
[2021-03-03 20:59:20,967] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:59:20,976] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.148 seconds
[2021-03-03 20:59:57,318] {scheduler_job.py:182} INFO - Started process (PID=46) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:59:57,319] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 20:59:57,319] {logging_mixin.py:104} INFO - [2021-03-03 20:59:57,319] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:59:57,490] {logging_mixin.py:104} INFO - [2021-03-03 20:59:57,490] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 20, in <module>
    start_date=days_ago(1),
NameError: name 'days_ago' is not defined
[2021-03-03 20:59:57,491] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 20:59:57,504] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.188 seconds
[2021-03-03 21:00:27,526] {scheduler_job.py:182} INFO - Started process (PID=76) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:00:27,526] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 21:00:27,527] {logging_mixin.py:104} INFO - [2021-03-03 21:00:27,527] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:00:27,656] {logging_mixin.py:104} INFO - [2021-03-03 21:00:27,656] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 20, in <module>
    start_date=days_ago(1),
NameError: name 'days_ago' is not defined
[2021-03-03 21:00:27,656] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:00:27,665] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.141 seconds
[2021-03-03 21:00:58,640] {scheduler_job.py:182} INFO - Started process (PID=108) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:00:58,640] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 21:00:58,641] {logging_mixin.py:104} INFO - [2021-03-03 21:00:58,640] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:00:58,759] {logging_mixin.py:104} INFO - [2021-03-03 21:00:58,759] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 20, in <module>
    start_date=days_ago(1),
NameError: name 'days_ago' is not defined
[2021-03-03 21:00:58,759] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:00:58,770] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.132 seconds
[2021-03-03 21:01:29,660] {scheduler_job.py:182} INFO - Started process (PID=138) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:01:29,660] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 21:01:29,661] {logging_mixin.py:104} INFO - [2021-03-03 21:01:29,661] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:01:29,776] {logging_mixin.py:104} INFO - [2021-03-03 21:01:29,775] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/save_to_minio/main2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/save_to_minio/main2.py", line 20, in <module>
    start_date=days_ago(1),
NameError: name 'days_ago' is not defined
[2021-03-03 21:01:29,776] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:01:29,785] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.126 seconds
[2021-03-03 21:02:00,626] {scheduler_job.py:182} INFO - Started process (PID=168) to work on /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:02:00,626] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/save_to_minio/main2.py for tasks to queue
[2021-03-03 21:02:00,626] {logging_mixin.py:104} INFO - [2021-03-03 21:02:00,626] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:02:00,626] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/save_to_minio/main2.py
[2021-03-03 21:02:00,627] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/save_to_minio/main2.py took 0.003 seconds
