[2021-03-07 13:07:25,116] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: check_minio_2.check_s3_for_file_in_s3 2021-03-06T00:00:00+00:00 [queued]>
[2021-03-07 13:07:25,126] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: check_minio_2.check_s3_for_file_in_s3 2021-03-06T00:00:00+00:00 [queued]>
[2021-03-07 13:07:25,126] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 13:07:25,126] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 13:07:25,126] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 13:07:25,137] {taskinstance.py:1063} INFO - Executing <Task(S3KeySensor): check_s3_for_file_in_s3> on 2021-03-06T00:00:00+00:00
[2021-03-07 13:07:25,141] {standard_task_runner.py:52} INFO - Started process 47 to run task
[2021-03-07 13:07:25,144] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'check_minio_2', 'check_s3_for_file_in_s3', '2021-03-06T00:00:00+00:00', '--job-id', '112', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/check_minio_2/main.py', '--cfg-path', '/tmp/tmpetxuq88l', '--error-file', '/tmp/tmpdmd4axs2']
[2021-03-07 13:07:25,144] {standard_task_runner.py:77} INFO - Job 112: Subtask check_s3_for_file_in_s3
[2021-03-07 13:07:25,216] {logging_mixin.py:104} INFO - Running <TaskInstance: check_minio_2.check_s3_for_file_in_s3 2021-03-06T00:00:00+00:00 [running]> on host ded171213b30
[2021-03-07 13:07:25,253] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=check_minio_2
AIRFLOW_CTX_TASK_ID=check_s3_for_file_in_s3
AIRFLOW_CTX_EXECUTION_DATE=2021-03-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-06T00:00:00+00:00
[2021-03-07 13:07:25,254] {s3_key.py:98} INFO - Poking for key : s3://my-first-bucket/*.txt*
[2021-03-07 13:07:25,254] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=local_minio
[2021-03-07 13:07:25,263] {base_aws.py:164} INFO - Credentials retrieved from extra_config
[2021-03-07 13:07:25,263] {base_aws.py:81} INFO - Creating session with aws_access_key_id=minio-access-key region_name=None
[2021-03-07 13:07:25,277] {base_aws.py:151} INFO - role_arn is None
[2021-03-07 13:07:25,365] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=local_minio
[2021-03-07 13:07:25,370] {base_aws.py:164} INFO - Credentials retrieved from extra_config
[2021-03-07 13:07:25,370] {base_aws.py:81} INFO - Creating session with aws_access_key_id=minio-access-key region_name=None
[2021-03-07 13:07:25,381] {base_aws.py:151} INFO - role_arn is None
[2021-03-07 13:07:25,425] {base.py:245} INFO - Success criteria met. Exiting.
[2021-03-07 13:07:25,431] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=check_minio_2, task_id=check_s3_for_file_in_s3, execution_date=20210306T000000, start_date=20210307T130725, end_date=20210307T130725
[2021-03-07 13:07:25,454] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-07 13:07:25,477] {local_task_job.py:146} INFO - Task exited with return code 0
