[2021-03-03 22:24:17,849] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio.generate_and_upload_to_s3 2021-03-03T22:19:06.110546+00:00 [queued]>
[2021-03-03 22:24:17,855] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio.generate_and_upload_to_s3 2021-03-03T22:19:06.110546+00:00 [queued]>
[2021-03-03 22:24:17,855] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 22:24:17,855] {taskinstance.py:1043} INFO - Starting attempt 2 of 2
[2021-03-03 22:24:17,855] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 22:24:17,864] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): generate_and_upload_to_s3> on 2021-03-03T22:19:06.110546+00:00
[2021-03-03 22:24:17,868] {standard_task_runner.py:52} INFO - Started process 63 to run task
[2021-03-03 22:24:17,870] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_minio', 'generate_and_upload_to_s3', '2021-03-03T22:19:06.110546+00:00', '--job-id', '74', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_minio/main.py', '--cfg-path', '/tmp/tmptvgt021s', '--error-file', '/tmp/tmp0vcwit6s']
[2021-03-03 22:24:17,870] {standard_task_runner.py:77} INFO - Job 74: Subtask generate_and_upload_to_s3
[2021-03-03 22:24:17,894] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_minio.generate_and_upload_to_s3 2021-03-03T22:19:06.110546+00:00 [running]> on host b5d0ebb2b610
[2021-03-03 22:24:17,915] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_minio
AIRFLOW_CTX_TASK_ID=generate_and_upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T22:19:06.110546+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T22:19:06.110546+00:00
[2021-03-03 22:24:17,916] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=local_minio
[2021-03-03 22:24:17,921] {base_aws.py:164} INFO - Credentials retrieved from extra_config
[2021-03-03 22:24:17,921] {base_aws.py:81} INFO - Creating session with aws_access_key_id=minio-access-key region_name=None
[2021-03-03 22:24:17,930] {base_aws.py:151} INFO - role_arn is None
[2021-03-03 22:24:17,982] {python.py:118} INFO - Done. Returned value was: None
[2021-03-03 22:24:18,029] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=generate_and_upload_to_s3, execution_date=20210303T221906, start_date=20210303T222417, end_date=20210303T222418
[2021-03-03 22:24:18,048] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-03 22:24:18,082] {local_task_job.py:146} INFO - Task exited with return code 0
