[2021-03-03 21:07:37,529] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.write_text_file 2021-03-03T21:07:34.819395+00:00 [queued]>
[2021-03-03 21:07:37,539] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.write_text_file 2021-03-03T21:07:34.819395+00:00 [queued]>
[2021-03-03 21:07:37,539] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:07:37,539] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-03 21:07:37,539] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:07:37,545] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): write_text_file> on 2021-03-03T21:07:34.819395+00:00
[2021-03-03 21:07:37,548] {standard_task_runner.py:52} INFO - Started process 48 to run task
[2021-03-03 21:07:37,550] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_minio_2', 'write_text_file', '2021-03-03T21:07:34.819395+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_mino_2/main.py', '--cfg-path', '/tmp/tmp107ii8l7', '--error-file', '/tmp/tmphafp9ec_']
[2021-03-03 21:07:37,551] {standard_task_runner.py:77} INFO - Job 44: Subtask write_text_file
[2021-03-03 21:07:37,573] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_minio_2.write_text_file 2021-03-03T21:07:34.819395+00:00 [running]> on host 4c61e128b408
[2021-03-03 21:07:37,601] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_minio_2
AIRFLOW_CTX_TASK_ID=write_text_file
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T21:07:34.819395+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T21:07:34.819395+00:00
[2021-03-03 21:07:37,601] {taskinstance.py:1455} ERROR - write() argument must be str, not dict
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/save_to_mino_2/main.py", line 41, in write_text_file
    fp.write(ds)
TypeError: write() argument must be str, not dict
[2021-03-03 21:07:37,602] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=save_to_minio_2, task_id=write_text_file, execution_date=20210303T210734, start_date=20210303T210737, end_date=20210303T210737
[2021-03-03 21:07:37,643] {local_task_job.py:146} INFO - Task exited with return code 1
