[2021-03-07 19:20:49,866] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_1.save 2021-03-06T00:00:00+00:00 [queued]>
[2021-03-07 19:20:49,879] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_1.save 2021-03-06T00:00:00+00:00 [queued]>
[2021-03-07 19:20:49,879] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:20:49,879] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 19:20:49,879] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:20:49,887] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): save> on 2021-03-06T00:00:00+00:00
[2021-03-07 19:20:49,892] {standard_task_runner.py:52} INFO - Started process 51 to run task
[2021-03-07 19:20:49,895] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_clickhouse_1', 'save', '2021-03-06T00:00:00+00:00', '--job-id', '155', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_clickhouse_1/main.py', '--cfg-path', '/tmp/tmpm9x_83s1', '--error-file', '/tmp/tmpps23nzes']
[2021-03-07 19:20:49,895] {standard_task_runner.py:77} INFO - Job 155: Subtask save
[2021-03-07 19:20:49,929] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_clickhouse_1.save 2021-03-06T00:00:00+00:00 [running]> on host 020f66ce59e6
[2021-03-07 19:20:49,965] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_clickhouse_1
AIRFLOW_CTX_TASK_ID=save
AIRFLOW_CTX_EXECUTION_DATE=2021-03-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-06T00:00:00+00:00
[2021-03-07 19:20:50,050] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_clickhouse_1, task_id=save, execution_date=20210306T000000, start_date=20210307T192049, end_date=20210307T192050
[2021-03-07 19:20:50,073] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-07 19:20:50,107] {local_task_job.py:146} INFO - Task exited with return code 0
