[2021-03-03 21:22:19,429] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_1.generate 2021-03-03T21:22:18.292274+00:00 [queued]>
[2021-03-03 21:22:19,440] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_1.generate 2021-03-03T21:22:18.292274+00:00 [queued]>
[2021-03-03 21:22:19,440] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:22:19,440] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-03 21:22:19,440] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:22:19,446] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): generate> on 2021-03-03T21:22:18.292274+00:00
[2021-03-03 21:22:19,450] {standard_task_runner.py:52} INFO - Started process 46 to run task
[2021-03-03 21:22:19,453] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test_1', 'generate', '2021-03-03T21:22:18.292274+00:00', '--job-id', '57', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test-1/main.py', '--cfg-path', '/tmp/tmpl1clb345', '--error-file', '/tmp/tmp83y8ahww']
[2021-03-03 21:22:19,453] {standard_task_runner.py:77} INFO - Job 57: Subtask generate
[2021-03-03 21:22:19,478] {logging_mixin.py:104} INFO - Running <TaskInstance: test_1.generate 2021-03-03T21:22:18.292274+00:00 [running]> on host 4c61e128b408
[2021-03-03 21:22:19,502] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=test_1
AIRFLOW_CTX_TASK_ID=generate
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T21:22:18.292274+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T21:22:18.292274+00:00
[2021-03-03 21:22:19,519] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=test_1, task_id=generate, execution_date=20210303T212218, start_date=20210303T212219, end_date=20210303T212219
[2021-03-03 21:22:19,541] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-03 21:22:19,586] {local_task_job.py:146} INFO - Task exited with return code 0
